/**
 * The project's look, rendered: what packages/design/tokens/project/ says,
 * turned into project.css and src/project.generated.ts.
 *
 * project/brand.json  a hand-authored Brand Package — the declared escape hatch
 * project/preset      a preset code (Sailor Studio; `nebutra apply --preset`)
 * neither             factory: styles.css as shipped, nothing overridden
 *
 * Shared by emit-project-run.ts (writes) and the tokens test (checks the
 * committed files are what this renders).
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { emitBrandCss } from "../brand-package/emit-css";
import { isDualModeBrand, normalizeBrandPackage } from "../brand-package/normalize";
import type { BrandPackage } from "../brand-package/types";
import { parsePreset } from "../preset/codec";
import { factoryBrandPackage } from "../preset/factory";
import type { Preset } from "../preset/knobs";
import { resolvePreset } from "../preset/resolve";

export interface RenderedProject {
  css: string;
  ts: string;
  warnings: string[];
}

const HEADER = `/*
 * GENERATED by packages/design/tokens/scripts/emit-project.mjs from
 * packages/design/tokens/project/ — do not edit. Change the look in Sailor
 * Studio and run \`nebutra apply --preset <code>\`.
 */
`;

function isNoop(preset: Preset): boolean {
  return preset.base === "factory" && Object.keys(preset).length === 1;
}

export function renderProject(packageRoot: string): RenderedProject {
  const dir = join(packageRoot, "project");
  const brandPath = join(dir, "brand.json");
  const presetPath = join(dir, "preset");
  const warnings: string[] = [];

  let brand: BrandPackage | null = null;
  let code: string | null = null;
  let mode: "system" | "light" | "dark" = "system";

  if (existsSync(brandPath)) {
    brand = normalizeBrandPackage(JSON.parse(readFileSync(brandPath, "utf8")));
  } else if (existsSync(presetPath)) {
    code = readFileSync(presetPath, "utf8").trim();
    const preset = parsePreset(code);
    if (preset.mode && preset.mode !== "base") mode = preset.mode;
    if (!isNoop(preset)) {
      const base =
        preset.base === "factory"
          ? factoryBrandPackage()
          : (JSON.parse(
              readFileSync(join(packageRoot, "brands", preset.base, "brand.json"), "utf8"),
            ) as BrandPackage);
      const resolved = resolvePreset(preset, base, { id: "project", name: "Project", code });
      brand = resolved.brand;
      warnings.push(...resolved.warnings);
    }
  }

  // A language with one palette is a one-mode site: the other mode would fall
  // through to the House tokens. Lock it to the mode its palette is for.
  const forced = brand && !isDualModeBrand(brand) ? (brand.darkDefault ? "dark" : "light") : null;

  const css = brand
    ? `${HEADER}${emitBrandCss(brand, { mode: "global" })}`
    : `${HEADER}\n/* factory: styles.css as shipped — nothing to override. */\n`;

  const ts = `/**
 * GENERATED by scripts/emit-project.mjs from project/ — do not edit.
 * Read by ThemeProvider for the project's default and locked modes.
 */
export const PROJECT_THEME = {
  preset: ${JSON.stringify(code)},
  defaultMode: ${JSON.stringify(forced ?? mode)},
  forcedMode: ${forced ? JSON.stringify(forced) : "undefined"},
} as const satisfies {
  preset: string | null;
  defaultMode: "system" | "light" | "dark";
  forcedMode: "light" | "dark" | undefined;
};
`;
  return { css, ts, warnings };
}
