/**
 * GENERATED by scripts/emit-project.mjs from project/ — do not edit.
 * Read by ThemeProvider for the project's default and locked modes.
 */
export const PROJECT_THEME = {
  preset: null,
  defaultMode: "system",
  forcedMode: undefined,
} as const satisfies {
  preset: string | null;
  defaultMode: "system" | "light" | "dark";
  forcedMode: "light" | "dark" | undefined;
};
